name: Deploy Python App to Server

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Optional: set up Python (if you want to run scripts on GitHub runner)
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Copy Python app to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 172.206.82.46
          username: azureuser   # e.g., azureuser
          key: ${{ secrets.AZURE_PRIVATE_KEY }}  # your SSH private key in GitHub secrets
          source: |
            app.py
            templates
            static
          target: "/home/azureuser/ateeq/python-app"
